import 'dotenv/config';
import {
  Account,
  Award,
  Certificate,
  CertificateTemplate,
  Event,
  EventTable,
  EmailTemplate,
  Project,
  Question,
  QuestionRegistration,
  QuestionTranslation,
  QuestionUser,
  PresentationSlide,
  Registration,
  Tshirt,
  TshirtGroup,
  TshirtGroupTranslation,
  TshirtTranslation,
  User,
  VoteCategory,
  UserProject,
  Attachment,
  Vote,
  Affiliation,
} from '@coolestprojects/database';

import { Sequelize } from 'sequelize-typescript';

export const sequelize = new Sequelize({
  dialect: process.env.DB_DIALECT as string,
  host: process.env.DB_HOST,
  port: Number(process.env.DB_PORT),
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  models: [
    Event,
    Award,
    Project,
    VoteCategory,
    Account,
    EventTable,
    User,
    UserProject,
    Tshirt,
    QuestionUser,
    Question,
    TshirtGroup,
    TshirtTranslation,
    QuestionTranslation,
    QuestionRegistration,
    Registration,
    TshirtGroupTranslation,
    Attachment,
    Vote,
    Affiliation,
    EmailTemplate,
    PresentationSlide,
    Certificate,
    CertificateTemplate,
  ],
  logging: process.env.NODE_ENV === 'production' ? false : console.log,
} as any);

await sequelize.authenticate();
