import { RegistrationDto } from '../dto/registration.dto';
import { Registration } from '@coolestprojects/database';
import { InfoDto } from '../dto/info.dto';
import { User } from '@coolestprojects/database';
import { Event } from '@coolestprojects/database';
import { MailerService } from '../mailer/mailer.service';
import { Question } from '@coolestprojects/database';
import { TokensService } from '../tokens/tokens.service';
import { Project } from '@coolestprojects/database';
import { QuestionRegistration } from '@coolestprojects/database';
import { Sequelize } from 'sequelize-typescript';
import { Voucher } from '@coolestprojects/database';
import { QuestionUser } from '@coolestprojects/database';
export declare class RegistrationService {
    private mailerService;
    private tokenService;
    private readonly sequelize;
    private readonly eventModel;
    private readonly projectModel;
    private readonly registrationModel;
    private readonly userModel;
    private readonly voucherModel;
    private readonly questionModel;
    private readonly questionUser;
    private readonly questionRegistrationModel;
    constructor(mailerService: MailerService, tokenService: TokensService, sequelize: Sequelize, eventModel: typeof Event, projectModel: typeof Project, registrationModel: typeof Registration, userModel: typeof User, voucherModel: typeof Voucher, questionModel: typeof Question, questionUser: typeof QuestionUser, questionRegistrationModel: typeof QuestionRegistration);
    create(info: InfoDto, createRegistrationDto: RegistrationDto): Promise<Registration | undefined>;
    activateRegistration(registrationID: number): Promise<User>;
    private validate;
}
