FROM httpd:latest


# Copy your configuration assets directly over
COPY ./proxy_templates/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./proxy_templates/proxy.conf /usr/local/apache2/conf/extra/proxy.conf