import { Event } from '@coolestprojects/database';
import { Tshirt } from '@coolestprojects/database';
import { TshirtGroup } from '@coolestprojects/database';
import { TshirtGroupTranslation } from '@coolestprojects/database';
import { TshirtTranslation } from '@coolestprojects/database';
import { Question } from '@coolestprojects/database';
import { QuestionTranslation } from '@coolestprojects/database';
import { Location } from '@coolestprojects/database';
import { EventTable } from '@coolestprojects/database';
import { EmailTemplate } from '@coolestprojects/database';
export declare function seedDatabase(eventModel: typeof Event, tshirtGroupModel: typeof TshirtGroup, questionModel: typeof Question, questionTranslationModel: typeof QuestionTranslation, tshirtModel: typeof Tshirt, tshirtGroupTranslationModel: typeof TshirtGroupTranslation, locationModel: typeof Location, eventTableModel: typeof EventTable, emailTemplateModel: typeof EmailTemplate, tshirtTranslationModel: typeof TshirtTranslation): Promise<void>;
