import { Event } from '@coolestprojects/database';
import { Tshirt } from '@coolestprojects/database';
import { TshirtGroup } from '@coolestprojects/database';
import { TshirtGroupTranslation } from '@coolestprojects/database';
import { TshirtTranslation } from '@coolestprojects/database';
import { Question } from '@coolestprojects/database';
import { QuestionTranslation } from '@coolestprojects/database';
import { Location } from '@coolestprojects/database';
import { EventTable } from '@coolestprojects/database';
import { EmailTemplate } from '@coolestprojects/database';
import { RegistrationService } from '../registration/registration.service';
import { TokensService } from '../tokens/tokens.service';
import { ParticipantService } from '../participant/participant.service';
export declare class EventCommand {
    private readonly eventModel;
    private readonly tshirtGroupModel;
    private readonly questionModel;
    private readonly questionTranslationModel;
    private readonly tshirtModel;
    private readonly tshirtGroupTranslationModel;
    private readonly tshirtTranslationModel;
    private readonly locationModel;
    private readonly eventTableModel;
    private readonly emailTemplateModel;
    private readonly registrationService;
    private readonly participantService;
    private readonly tokenService;
    constructor(eventModel: typeof Event, tshirtGroupModel: typeof TshirtGroup, questionModel: typeof Question, questionTranslationModel: typeof QuestionTranslation, tshirtModel: typeof Tshirt, tshirtGroupTranslationModel: typeof TshirtGroupTranslation, tshirtTranslationModel: typeof TshirtTranslation, locationModel: typeof Location, eventTableModel: typeof EventTable, emailTemplateModel: typeof EmailTemplate, registrationService: RegistrationService, participantService: ParticipantService, tokenService: TokensService);
    initEventDB(): Promise<void>;
}
