version: '3.8'

services:
  workspace:
    image: node:26
    container_name: ${PROJECT_NAME:-coolestproject-dev}-workspace

    environment:
      # Database configuration (admin & api)
      DB_DIALECT: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: coolestproject
      DB_USER: coolestproject
      DB_PASSWORD: Se84KCCCJlnfkdfv

      # AdminJS configuration
      ADMINJS_COOKIE_SECRET: nic2;To97Di\lF8zC'V{'[_
      ADMINJS_PORT: 3000

    volumes:
      - ..:/workspace:cached

    working_dir: /workspace

    command: sleep infinity

    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"

    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: ${PROJECT_NAME:-coolestproject-dev}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: coolestproject
      MYSQL_DATABASE: coolestproject
      MYSQL_USER: coolestproject
      MYSQL_PASSWORD: Se84KCCCJlnfkdfv
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: