version: '3.8'

services:
  workspace:
    image: node:26

    environment:
      DB_DIALECT: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: coolestproject
      DB_USER: coolestproject
      DB_PASSWORD: Se84KCCCJlnfkdfv

    volumes:
      - ..:/workspace:cached

    working_dir: /workspace

    command: sleep infinity

    ports:
      - "3000:3000"
      - "3001:3001"

    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: ${PROJECT_NAME:-coolestproject}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: coolestproject
      MYSQL_DATABASE: coolestproject
      MYSQL_USER: coolestproject
      MYSQL_PASSWORD: Se84KCCCJlnfkdfv
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: