import { Question } from './question.model.js';
import { Tshirt } from './tshirt.model.js';
import { BaseEventModel } from './base_event.model.js';
export declare class Registration extends BaseEventModel {
    eventId: number;
    tshirtId: number;
    tshirt: Tshirt;
    questions: Question[];
    language: string;
    postalcode: number;
    municipality_name: string;
    street: string;
    house_number: string;
    box_number: string;
    email: string;
    firstname: string;
    lastname: string;
    sex: string;
    birthmonth: Date;
    via: string;
    medical: string;
    gsm: string;
    gsm_guardian: string;
    internalinfo: string;
    email_guardian: string;
    project_code: string;
    waiting_list: boolean;
    project_name: string;
    project_descr: string;
    project_lang: string;
    project_type: string;
    max_tokens: number;
}
